[versions]
junit-jupiter = "5.12.1"
lombok = "1.18.42"
commons-io = "2.21.0"
gson = "2.10.1"
reflections = "0.10.2"
asmplus = "1.5.0"
jlib = "1.0.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
commons-io = { module = "commons-io:commons-io", version.ref = "commons-io" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
reflections = { module = "org.reflections:reflections", version.ref = "reflections" }
asmplus = { module = "me.exeos:asmplus", version.ref = "asmplus" }
jlib = { module = "me.exeos:jlib", version.ref = "jlib" }
